import "server-only";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import type { DeckReviewResult } from "@/types/deck";

export type StoredDeckReview = {
  id: string;
  deckId: string;
  deckHash: string;
  provider: string;
  model: string;
  promptVersion: string;
  result: DeckReviewResult;
  createdAt: string;
};

type ReviewRow = {
  id: string;
  deck_id: string;
  deck_hash: string;
  provider: string;
  model: string;
  prompt_version: string;
  result: DeckReviewResult;
  created_at: string;
};

function toStoredReview(row: ReviewRow): StoredDeckReview {
  return {
    id: row.id,
    deckId: row.deck_id,
    deckHash: row.deck_hash,
    provider: row.provider,
    model: row.model,
    promptVersion: row.prompt_version,
    result: row.result,
    createdAt: row.created_at,
  };
}

/** Returns a cached review for this exact deck+hash, if one already exists. */
export async function findCachedReview(deckId: string, deckHash: string): Promise<StoredDeckReview | null> {
  const supabase = getSupabaseServerClient();
  const { data } = await supabase
    .from("deck_reviews")
    .select()
    .eq("deck_id", deckId)
    .eq("deck_hash", deckHash)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle<ReviewRow>();

  return data ? toStoredReview(data) : null;
}

/** Returns the most recent review for a deck regardless of hash, for the "latest" endpoint. */
export async function findLatestReview(deckId: string): Promise<StoredDeckReview | null> {
  const supabase = getSupabaseServerClient();
  const { data } = await supabase
    .from("deck_reviews")
    .select()
    .eq("deck_id", deckId)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle<ReviewRow>();

  return data ? toStoredReview(data) : null;
}

export async function saveReview(params: {
  deckId: string;
  ownerId: string;
  deckHash: string;
  provider: string;
  model: string;
  promptVersion: string;
  result: DeckReviewResult;
}): Promise<StoredDeckReview> {
  const supabase = getSupabaseServerClient();
  const { data, error } = await supabase
    .from("deck_reviews")
    .insert({
      deck_id: params.deckId,
      owner_id: params.ownerId,
      deck_hash: params.deckHash,
      provider: params.provider,
      model: params.model,
      prompt_version: params.promptVersion,
      result: params.result,
    })
    .select()
    .single<ReviewRow>();

  if (error || !data) {
    throw new Error(`Failed to save AI review: ${error?.message ?? "unknown error"}`);
  }
  return toStoredReview(data);
}

/** Counts reviews generated by this owner (across all their decks) in the last 24 hours. */
export async function countReviewsInLast24Hours(ownerId: string): Promise<number> {
  const supabase = getSupabaseServerClient();
  const since = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
  const { count } = await supabase
    .from("deck_reviews")
    .select("id", { count: "exact", head: true })
    .eq("owner_id", ownerId)
    .gte("created_at", since);
  return count ?? 0;
}
